version: "3.8"
services:
  mongodb:
    image: "mongo:4.2.10-bionic"
    restart: always
    networks:
      - backend
    volumes:
      - ~/wmd-data/mongodb:/data/db
  controller:
    build: "./controller"
    restart: always
    depends_on:
      - mongodb
      - reauth
    env_file:
      - ./controller/.env
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      REAUTH_BASE_URL: http://reauth:6660
      MONGO_CONN_STRING: mongodb://mongodb
      VIRTUAL_HOST: ${SERVER_VIRTUAL_HOST}
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: ${SERVER_VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${DEFAULT_EMAIL}
    networks:
      - backend
    volumes:
      - ~/wmd-data/mongodb:/data/db:ro
      - ~/wmd-snapshots:/snapshots
  webapp:
    restart: always
    build: "./webapp"
    depends_on:
      - controller
      - reauth
    env_file:
      - ./webapp/.env
    expose:
      - 80
    environment:
      VIRTUAL_HOST: ${WEB_VIRTUAL_HOST}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${WEB_VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${DEFAULT_EMAIL}
    networks:
      - backend
  nginx-proxy-letsencrypt:
    image: "jrcs/letsencrypt-nginx-proxy-companion:latest"
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: ${DEFAULT_EMAIL}
  nginx-proxy:
    image: "jwilder/nginx-proxy:alpine"
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - backend
  reauth:
    build: "./reauth"
    env_file:
      - ./reauth/.env
    depends_on:
      - mongodb
    expose:
      - 6660
    ports:
      - 6660:6660
    environment:
      MONGO_CONN_STRING: mongodb://mongodb
      VIRTUAL_HOST: ${REAUTH_VIRTUAL_HOST}
      VIRTUAL_PORT: 6660
      LETSENCRYPT_HOST: ${REAUTH_VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${DEFAULT_EMAIL}
    networks:
      - backend
networks:
  backend:
    driver: bridge
