version: "3.8"
services:
  mongodb:
    build:
      context: "."
      dockerfile: "./mongodb-Dockerfile"
    restart: always
    networks:
      - backend
    volumes:
      - ~/wmd-data/mongodb:/data/db
  controller:
    build: "./controller"
    restart: always
    ports:
      - "8080:8080"
    environment:
      MONGO_CONN_STRING: dummy
      WAIT_HOSTS: mongodb:27017
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 10
      WAIT_HOST_CONNECT_TIMEOUT: 30
    networks:
      - backend
  webapp:
    restart: always
    build: "./webapp"
    ports:
      - "80:80"
networks:
  backend:
    driver: bridge
